CREATE OR REPLACE TABLE temp_users AS
SELECT * 
FROM users
WHERE 1=0; 

INSERT INTO temp_users (USER_ID, USER_NAME, DATE_OF_BIRTH, SIGN_UP_DATE, UPDATED_AT) 
SELECT USER_ID, USER_NAME, DATE_OF_BIRTH, SIGN_UP_DATE, UPDATED_AT
FROM (
    SELECT USER_ID, USER_NAME, DATE_OF_BIRTH, SIGN_UP_DATE, UPDATED_AT,
           ROW_NUMBER() OVER (PARTITION BY USER_ID ORDER BY UPDATED_AT DESC) AS row_num
    FROM users
)
WHERE row_num = 1;

TRUNCATE TABLE users;

INSERT INTO users
SELECT * FROM temp_users;

DROP TABLE IF EXISTS temp_users;