CREATE OR REPLACE TABLE temp_utms AS
SELECT * 
FROM utms
WHERE 1=0; 

INSERT INTO temp_utms (UTM_ID, UTM_SOURCE, UTM_MEDIUM, UTM_CAMPAIGN, UTM_TERM, UTM_CONTENT, UPDATED_AT) 
SELECT UTM_ID, UTM_SOURCE, UTM_MEDIUM, UTM_CAMPAIGN, UTM_TERM, UTM_CONTENT, UPDATED_AT
FROM (
    SELECT UTM_ID, UTM_SOURCE, UTM_MEDIUM, UTM_CAMPAIGN, UTM_TERM, UTM_CONTENT, UPDATED_AT,
           ROW_NUMBER() OVER (PARTITION BY UTM_ID ORDER BY UPDATED_AT DESC) AS row_num
    FROM utms
)
WHERE row_num = 1;

TRUNCATE TABLE utms;

INSERT INTO utms
SELECT * FROM temp_utms;

DROP TABLE IF EXISTS temp_utms;