TRUNCATE TABLE IF EXISTS payments;
TRUNCATE TABLE IF EXISTS bookings;
TRUNCATE TABLE IF EXISTS daily_planet_report;
TRUNCATE TABLE IF EXISTS promo_codes;
TRUNCATE TABLE IF EXISTS routes;
TRUNCATE TABLE IF EXISTS customers;
TRUNCATE TABLE IF EXISTS planets;
