NUTRITION_DATABASE = {
    "milk": {"protein": 3.4, "carbs": 5.0, "fat": 3.5, "calories": 64, "unit": "100ml"},
    "eggs": {"protein": 6.0, "carbs": 0.6, "fat": 5.0, "calories": 70, "unit": "piece"},
    "cheese": {
        "protein": 7.0,
        "carbs": 0.4,
        "fat": 9.0,
        "calories": 113,
        "unit": "slice",
    },
    "yogurt": {
        "protein": 10.0,
        "carbs": 4.0,
        "fat": 0.4,
        "calories": 59,
        "unit": "100g",
    },
    "butter": {
        "protein": 0.9,
        "carbs": 0.1,
        "fat": 81.0,
        "calories": 717,
        "unit": "100g",
    },
    "cream cheese": {
        "protein": 6.0,
        "carbs": 4.0,
        "fat": 34.0,
        "calories": 342,
        "unit": "100g",
    },
    "sour cream": {
        "protein": 2.4,
        "carbs": 4.6,
        "fat": 20.0,
        "calories": 193,
        "unit": "100g",
    },
    "cottage cheese": {
        "protein": 11.0,
        "carbs": 3.4,
        "fat": 4.3,
        "calories": 98,
        "unit": "100g",
    },
    "mozzarella": {
        "protein": 22.0,
        "carbs": 2.2,
        "fat": 22.0,
        "calories": 280,
        "unit": "100g",
    },
    "cheddar": {
        "protein": 25.0,
        "carbs": 1.3,
        "fat": 33.0,
        "calories": 403,
        "unit": "100g",
    },
    "chicken breast": {
        "protein": 31.0,
        "carbs": 0.0,
        "fat": 3.6,
        "calories": 165,
        "unit": "100g",
    },
    "salmon": {
        "protein": 25.0,
        "carbs": 0.0,
        "fat": 13.0,
        "calories": 208,
        "unit": "100g",
    },
    "tuna": {
        "protein": 29.0,
        "carbs": 0.0,
        "fat": 6.0,
        "calories": 184,
        "unit": "100g",
    },
    "shrimp": {
        "protein": 24.0,
        "carbs": 0.2,
        "fat": 0.3,
        "calories": 99,
        "unit": "100g",
    },
    "turkey breast": {
        "protein": 29.0,
        "carbs": 0.0,
        "fat": 1.0,
        "calories": 135,
        "unit": "100g",
    },
    "beef steak": {
        "protein": 26.0,
        "carbs": 0.0,
        "fat": 17.0,
        "calories": 271,
        "unit": "100g",
    },
    "pork chop": {
        "protein": 26.0,
        "carbs": 0.0,
        "fat": 14.0,
        "calories": 242,
        "unit": "100g",
    },
    "bacon": {
        "protein": 37.0,
        "carbs": 1.4,
        "fat": 42.0,
        "calories": 541,
        "unit": "100g",
    },
    "ham": {"protein": 22.0, "carbs": 1.5, "fat": 5.0, "calories": 145, "unit": "100g"},
    "tofu": {"protein": 8.0, "carbs": 1.9, "fat": 4.8, "calories": 76, "unit": "100g"},
    "apple": {
        "protein": 0.3,
        "carbs": 14.0,
        "fat": 0.2,
        "calories": 52,
        "unit": "piece",
    },
    "banana": {
        "protein": 1.1,
        "carbs": 23.0,
        "fat": 0.3,
        "calories": 89,
        "unit": "piece",
    },
    "orange": {
        "protein": 0.9,
        "carbs": 12.0,
        "fat": 0.1,
        "calories": 47,
        "unit": "piece",
    },
    "strawberries": {
        "protein": 0.7,
        "carbs": 7.7,
        "fat": 0.3,
        "calories": 32,
        "unit": "100g",
    },
    "blueberries": {
        "protein": 0.7,
        "carbs": 14.0,
        "fat": 0.3,
        "calories": 57,
        "unit": "100g",
    },
    "grapes": {
        "protein": 0.7,
        "carbs": 18.0,
        "fat": 0.2,
        "calories": 69,
        "unit": "100g",
    },
    "watermelon": {
        "protein": 0.6,
        "carbs": 8.0,
        "fat": 0.2,
        "calories": 30,
        "unit": "100g",
    },
    "pineapple": {
        "protein": 0.5,
        "carbs": 13.0,
        "fat": 0.1,
        "calories": 50,
        "unit": "100g",
    },
    "mango": {
        "protein": 0.8,
        "carbs": 15.0,
        "fat": 0.4,
        "calories": 60,
        "unit": "100g",
    },
    "peach": {
        "protein": 0.9,
        "carbs": 10.0,
        "fat": 0.3,
        "calories": 39,
        "unit": "piece",
    },
    "pear": {
        "protein": 0.4,
        "carbs": 15.0,
        "fat": 0.1,
        "calories": 57,
        "unit": "piece",
    },
    "kiwi": {
        "protein": 1.1,
        "carbs": 15.0,
        "fat": 0.5,
        "calories": 61,
        "unit": "piece",
    },
    "avocado": {
        "protein": 2.0,
        "carbs": 9.0,
        "fat": 15.0,
        "calories": 160,
        "unit": "piece",
    },
    "broccoli": {
        "protein": 2.8,
        "carbs": 7.0,
        "fat": 0.4,
        "calories": 34,
        "unit": "100g",
    },
    "carrots": {
        "protein": 0.9,
        "carbs": 10.0,
        "fat": 0.2,
        "calories": 41,
        "unit": "100g",
    },
    "spinach": {
        "protein": 2.9,
        "carbs": 3.6,
        "fat": 0.4,
        "calories": 23,
        "unit": "100g",
    },
    "tomatoes": {
        "protein": 0.9,
        "carbs": 3.9,
        "fat": 0.2,
        "calories": 18,
        "unit": "100g",
    },
    "bell pepper": {
        "protein": 1.0,
        "carbs": 6.0,
        "fat": 0.3,
        "calories": 31,
        "unit": "piece",
    },
    "cucumber": {
        "protein": 0.7,
        "carbs": 3.6,
        "fat": 0.1,
        "calories": 16,
        "unit": "100g",
    },
    "lettuce": {
        "protein": 1.4,
        "carbs": 2.9,
        "fat": 0.2,
        "calories": 15,
        "unit": "100g",
    },
    "onion": {"protein": 1.1, "carbs": 9.0, "fat": 0.1, "calories": 40, "unit": "100g"},
    "garlic": {
        "protein": 6.4,
        "carbs": 33.0,
        "fat": 0.5,
        "calories": 149,
        "unit": "100g",
    },
    "mushrooms": {
        "protein": 3.1,
        "carbs": 3.3,
        "fat": 0.3,
        "calories": 22,
        "unit": "100g",
    },
    "zucchini": {
        "protein": 1.2,
        "carbs": 3.1,
        "fat": 0.3,
        "calories": 17,
        "unit": "100g",
    },
    "cauliflower": {
        "protein": 1.9,
        "carbs": 5.0,
        "fat": 0.3,
        "calories": 25,
        "unit": "100g",
    },
    "green beans": {
        "protein": 1.8,
        "carbs": 7.0,
        "fat": 0.1,
        "calories": 31,
        "unit": "100g",
    },
    "asparagus": {
        "protein": 2.2,
        "carbs": 3.9,
        "fat": 0.2,
        "calories": 20,
        "unit": "100g",
    },
    "kale": {"protein": 4.3, "carbs": 9.0, "fat": 0.9, "calories": 49, "unit": "100g"},
    "bread": {
        "protein": 2.5,
        "carbs": 13.0,
        "fat": 0.9,
        "calories": 69,
        "unit": "slice",
    },
    "rice": {
        "protein": 2.7,
        "carbs": 28.0,
        "fat": 0.3,
        "calories": 130,
        "unit": "100g",
    },
    "pasta": {
        "protein": 5.0,
        "carbs": 25.0,
        "fat": 0.9,
        "calories": 131,
        "unit": "100g",
    },
    "oats": {
        "protein": 13.0,
        "carbs": 67.0,
        "fat": 7.0,
        "calories": 389,
        "unit": "100g",
    },
    "quinoa": {
        "protein": 4.4,
        "carbs": 21.0,
        "fat": 1.9,
        "calories": 120,
        "unit": "100g",
    },
    "bagel": {
        "protein": 9.0,
        "carbs": 53.0,
        "fat": 1.5,
        "calories": 257,
        "unit": "piece",
    },
    "tortilla": {
        "protein": 3.0,
        "carbs": 19.0,
        "fat": 2.5,
        "calories": 104,
        "unit": "piece",
    },
    "cereal": {
        "protein": 7.0,
        "carbs": 84.0,
        "fat": 2.0,
        "calories": 379,
        "unit": "100g",
    },
    "crackers": {
        "protein": 7.0,
        "carbs": 68.0,
        "fat": 13.0,
        "calories": 435,
        "unit": "100g",
    },
    "couscous": {
        "protein": 3.8,
        "carbs": 23.0,
        "fat": 0.2,
        "calories": 112,
        "unit": "100g",
    },
    "black beans": {
        "protein": 8.9,
        "carbs": 24.0,
        "fat": 0.5,
        "calories": 132,
        "unit": "100g",
    },
    "chickpeas": {
        "protein": 8.9,
        "carbs": 27.0,
        "fat": 2.6,
        "calories": 164,
        "unit": "100g",
    },
    "lentils": {
        "protein": 9.0,
        "carbs": 20.0,
        "fat": 0.4,
        "calories": 116,
        "unit": "100g",
    },
    "kidney beans": {
        "protein": 8.7,
        "carbs": 23.0,
        "fat": 0.5,
        "calories": 127,
        "unit": "100g",
    },
    "almonds": {
        "protein": 21.0,
        "carbs": 22.0,
        "fat": 50.0,
        "calories": 579,
        "unit": "100g",
    },
    "walnuts": {
        "protein": 15.0,
        "carbs": 14.0,
        "fat": 65.0,
        "calories": 654,
        "unit": "100g",
    },
    "peanuts": {
        "protein": 26.0,
        "carbs": 16.0,
        "fat": 49.0,
        "calories": 567,
        "unit": "100g",
    },
    "cashews": {
        "protein": 18.0,
        "carbs": 30.0,
        "fat": 44.0,
        "calories": 553,
        "unit": "100g",
    },
    "peanut butter": {
        "protein": 25.0,
        "carbs": 20.0,
        "fat": 50.0,
        "calories": 588,
        "unit": "100g",
    },
    "hummus": {
        "protein": 8.0,
        "carbs": 14.0,
        "fat": 10.0,
        "calories": 166,
        "unit": "100g",
    },
    "honey": {
        "protein": 0.3,
        "carbs": 82.0,
        "fat": 0.0,
        "calories": 304,
        "unit": "100g",
    },
    "jam": {"protein": 0.4, "carbs": 69.0, "fat": 0.1, "calories": 278, "unit": "100g"},
    "mayonnaise": {
        "protein": 1.0,
        "carbs": 0.6,
        "fat": 75.0,
        "calories": 680,
        "unit": "100g",
    },
    "ketchup": {
        "protein": 1.0,
        "carbs": 27.0,
        "fat": 0.1,
        "calories": 112,
        "unit": "100g",
    },
    "mustard": {
        "protein": 4.4,
        "carbs": 5.3,
        "fat": 6.4,
        "calories": 66,
        "unit": "100g",
    },
    "olive oil": {
        "protein": 0.0,
        "carbs": 0.0,
        "fat": 100.0,
        "calories": 884,
        "unit": "100g",
    },
    "chocolate": {
        "protein": 5.0,
        "carbs": 61.0,
        "fat": 31.0,
        "calories": 546,
        "unit": "100g",
    },
    "granola": {
        "protein": 10.0,
        "carbs": 68.0,
        "fat": 15.0,
        "calories": 471,
        "unit": "100g",
    },
    "potato chips": {
        "protein": 6.6,
        "carbs": 53.0,
        "fat": 35.0,
        "calories": 536,
        "unit": "100g",
    },
    "popcorn": {
        "protein": 12.0,
        "carbs": 78.0,
        "fat": 4.5,
        "calories": 387,
        "unit": "100g",
    },
    "orange juice": {
        "protein": 0.7,
        "carbs": 10.0,
        "fat": 0.2,
        "calories": 45,
        "unit": "100ml",
    },
    "coffee": {
        "protein": 0.1,
        "carbs": 0.0,
        "fat": 0.0,
        "calories": 2,
        "unit": "100ml",
    },
    "tea": {"protein": 0.0, "carbs": 0.3, "fat": 0.0, "calories": 1, "unit": "100ml"},
    "coconut milk": {
        "protein": 2.3,
        "carbs": 6.0,
        "fat": 24.0,
        "calories": 230,
        "unit": "100ml",
    },
    "almond milk": {
        "protein": 0.4,
        "carbs": 0.3,
        "fat": 1.1,
        "calories": 17,
        "unit": "100ml",
    },
    "pizza slice": {
        "protein": 12.0,
        "carbs": 33.0,
        "fat": 10.0,
        "calories": 266,
        "unit": "slice",
    },
    "burger patty": {
        "protein": 17.0,
        "carbs": 0.0,
        "fat": 20.0,
        "calories": 250,
        "unit": "piece",
    },
    "hot dog": {
        "protein": 10.0,
        "carbs": 2.0,
        "fat": 26.0,
        "calories": 290,
        "unit": "piece",
    },
    "french fries": {
        "protein": 3.4,
        "carbs": 41.0,
        "fat": 15.0,
        "calories": 312,
        "unit": "100g",
    },
    "mac and cheese": {
        "protein": 9.0,
        "carbs": 26.0,
        "fat": 13.0,
        "calories": 267,
        "unit": "100g",
    },
    "lasagna": {
        "protein": 8.0,
        "carbs": 13.0,
        "fat": 8.0,
        "calories": 161,
        "unit": "100g",
    },
    "soup": {"protein": 2.5, "carbs": 7.0, "fat": 2.0, "calories": 52, "unit": "100ml"},
    "sushi roll": {
        "protein": 6.0,
        "carbs": 30.0,
        "fat": 3.5,
        "calories": 175,
        "unit": "piece",
    },
    "burrito": {
        "protein": 14.0,
        "carbs": 40.0,
        "fat": 12.0,
        "calories": 326,
        "unit": "piece",
    },
    "sandwich": {
        "protein": 15.0,
        "carbs": 30.0,
        "fat": 8.0,
        "calories": 256,
        "unit": "piece",
    },
    "sweet potato": {
        "protein": 1.6,
        "carbs": 20.0,
        "fat": 0.1,
        "calories": 86,
        "unit": "100g",
    },
    "potato": {
        "protein": 2.0,
        "carbs": 17.0,
        "fat": 0.1,
        "calories": 77,
        "unit": "100g",
    },
    "corn": {"protein": 3.4, "carbs": 19.0, "fat": 1.5, "calories": 96, "unit": "100g"},
    "peas": {"protein": 5.4, "carbs": 14.0, "fat": 0.4, "calories": 81, "unit": "100g"},
    "edamame": {
        "protein": 11.0,
        "carbs": 8.9,
        "fat": 5.2,
        "calories": 122,
        "unit": "100g",
    },
    "pickles": {
        "protein": 0.3,
        "carbs": 2.3,
        "fat": 0.2,
        "calories": 11,
        "unit": "100g",
    },
    "soy sauce": {
        "protein": 8.1,
        "carbs": 4.9,
        "fat": 0.0,
        "calories": 53,
        "unit": "100ml",
    },
}

